config/routes.rb
Rails.application.routes.draw do

  get 'teamevents/index'

  get 'embed/index'

  root 'home#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'share' => 'embed#index'
  get 'eventstanding/:event_id' => 'embed#eventstandings', as: :sharestandings
  get 'eventresults/:event_id' => 'embed#eventresults', as: :shareresults

  get 'standings/:event_id' => 'events#showstanding', as: :standing
  
  get 'set/:event_id' => 'events#setresults', as: :set
  post 'set/:event_id' => 'events#createresults'
  delete 'set/:event_id' => 'events#destroyresults'
  
  get 'ae/:event_id' => 'events#showathlete', as: :ae
  post 'ae/:event_id' => 'events#createathlete'
  delete 'ae/:event_id' => 'events#destroyathlete'
  
  get 'at/:event_id' => 'events#showteam', as: :at
  post 'at/:event_id' => 'events#createteam'
  delete 'at/:event_id' => 'events#destroyteam'

    resources :athletes
	
    resources :teams
    resources :events

end

app/models/athlete.rb
class Athlete < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	belongs_to :team
	has_many :athleteevents
	has_many :events, through: :athleteevents
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
	before_filter :require_authorization

	add_breadcrumb "Home", :root_path
	add_breadcrumb "Athletes", :athletes_path
	def index
		@athletes = Athlete.paginate(:page => params[:page], :per_page => 20)
	end

	def new
		@athlete = Athlete.new
	end

	def create
		params[:athlete][:birthday] = params[:yyyy]+'/'+params[:mm]+'/'+params[:dd]
		@athlete = Athlete.create(athlete_params)
		if @athlete.save
	  		redirect_to athletes_path
	  	else
	  		render 'new'
	  	end
	end

	def show
		@athlete = Athlete.find(params[:id])
		add_breadcrumb @athlete.name, athlete_path(@athlete.id)
	end
	
	def edit
		@athlete = Athlete.find(params[:id])
		@gender = @athlete.gender
		@birthday = @athlete.birthday
		@themont = @birthday.strftime('%B')
	end

	def update
	    params[:athlete][:birthday] = params[:yyyy]+'/'+params[:mm]+'/'+params[:dd]
		@athlete = Athlete.find(params[:id])

		if @athlete.update(athlete_params)
			redirect_to @athlete
		else
			render 'edit'
		end

	end

	def destroy
		@athlete = Athlete.find(params[:id])
		@athlete.destroy

		redirect_to athletes_path
	end

	private
		def athlete_params
			params.require(:athlete).permit(:name, :birthday, :city, :province, :team_id, :number, :image, :address, :phone, :email, :gender)
		end

	def require_authorization
		redirect_to root_path unless logged_in? # or whatever you want to check
	end
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/views/athletes/_form.html.erb
<%= form_for(@athlete, :html => {:class => "form-horizontal"}) do |f| %>

	<div class="form-group">
		<%= f.label :name, class: "col-sm-2 control-label" %>
		<div class="col-sm-6">
			<%= f.text_field :name, class: "form-control", placeholder: "Name" %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :gender, class: "col-sm-2 control-label" %>
		<div class="col-sm-2">
			
			<% if params[:action] == "edit" %>
			
			<%= select_tag "athlete[gender]", options_for_select([ "Male", "Female" ], @gender), class: "form-control" %>
				
			<% else %>
			<select name="athlete[gender]" class="form-control">
				<option value="Male">Male</option>
				<option value="Female">Female</option>
			</select>
			<% end %>
			
		</div>
	</div>

	<div class="form-group">
		<%= f.label :birtday, class: "col-sm-2 control-label" %>
		<% if params[:action] == "edit" %>
			<div class="col-sm-2">
				<%= select_tag "dd", options_for_select((1..31).map {|d| [d, d]}, @birthday.strftime('%-d')), class: "form-control", id: "hari" %>
			</div>
			<div class="col-sm-3">
				<%= select_tag "mm", options_for_select((1..12).map {|m| [Date::MONTHNAMES[m], m]}, @birthday.strftime('%-m')), class: "form-control", id: "bulan" %>
			</div>
			<div class="col-sm-2">
				<%= select_tag "yyyy", options_for_select((1900..2016).map {|y| [y, y]}, @birthday.strftime('%Y')), class: "form-control", id: "tahun" %>
			</div>
		<% else %>
			<div class="col-sm-2">
				<%= select_tag "dd", options_for_select((1..31).map {|d| [d, d]}), class: "form-control", id: "hari" %>
			</div>
			<div class="col-sm-3">
				<%= select_tag "mm", options_for_select((1..12).map {|m| [Date::MONTHNAMES[m], m]}), class: "form-control", id: "bulan" %>
			</div>
			<div class="col-sm-2">
				<%= select_tag "yyyy", options_for_select((1900..2016).map {|y| [y, y]}), class: "form-control", id: "tahun" %>
			</div>
		<% end %>
		
	</div>

	<div class="form-group">
		<%= f.label :address, class: "col-sm-2 control-label" %>
		<div class="col-sm-6">
			<%= f.text_area :address, class: "form-control", placeholder: "Address" %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :city, class: "col-sm-2 control-label" %>
		<div class="col-sm-3">
			<%= f.text_field :city, class: "form-control", placeholder: "City" %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :province, class: "col-sm-2 control-label" %>
		<div class="col-sm-4">
			<%= f.text_field :province, class: "form-control", placeholder: "Province" %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :team, class: "col-sm-2 control-label" %>
		<div class="col-sm-4">
			<%= select("athlete", "team_id", Team.all.collect {|p| [ p.name, p.id ] }, {prompt: 'Select Team'}, class: "form-control") %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :email, class: "col-sm-2 control-label" %>
		<div class="col-sm-4">
			<%= f.text_field :email, class: "form-control", placeholder: "Email Address" %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :phone, class: "col-sm-2 control-label" %>
		<div class="col-sm-4">
			<%= f.text_field :phone, class: "form-control", placeholder: "Phone Number" %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :number, class: "col-sm-2 control-label" %>
		<div class="col-sm-4">
			<%= f.text_field :number, class: "form-control", placeholder: "Athlete Number" %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :image, class: "col-sm-2 control-label" %>
		<div class="col-sm-5">
			<%= f.file_field :image, class: "form-control" %>
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-8">
		  <%= f.submit "Submit", class: "btn btn-default" %>
		</div>
	</div>
<% end %>

app/views/athletes/edit.html.erb
<% provide(:title, "Edit") %>
<h2>Edit Athlete Data</h2>
<%= render 'form' %>

app/views/athletes/index.html.erb
<% provide(:title, "Atlit") %>
<ol class="breadcrumb">
    <%= render_breadcrumbs :tag => :li, :separator => "" %>
  </ol>
<% if @athletes.present? %>
<div class="pull-left"><h2>Daftar Atlit</h2></div>
<div class="pull-right"><%= link_to (fa_icon "plus-circle", text: "Add New"), new_athlete_path, class: "btn btn-sm btn-default" %></div>
<table class="table table-hover">
  <thead>
  <tr class="active">
  <th>
  		No
  	</th>
  	<th>
  		Name
  	</th>
  	<th>
  		City
  	</th>
  	<th>
  		Actions
  	</th>
  </tr>

  </thead>
  <tbody>



	<% @athletes.each_with_index do |a, index| %>
	<tr>
	<td class="athletes no-<%= a.id %> col-md-1"><%= @athletes.offset + index + 1 %></td>
	<td class="name col-md-4"><%= a.name %></td>
	<td class="city col-md-3"><%= a.city %></td>
	<td class="edit col-md-2">
  <%= link_to (fa_icon "pencil"), edit_athlete_path(a.id), class: "btn btn-sm btn-warning" %>
  <%= link_to (fa_icon "eye"), athlete_path(a.id), class: "btn btn-sm btn-default" %>
  <%= link_to (fa_icon "trash"), athlete_path(a), method: :delete, data: { confirm: "Apakah anda ingin menghapus ?" }, class: "btn btn-sm btn-danger"  %>
  </td>
	</tr>
	<% end %>




  </tbody>
</table>
<% else %>
	<div class="alert alert-warning"> There are no athletes. <%= link_to "Create One Now.", new_athlete_path, class: "btn btn-sm btn-default" %> </div>
<% end %>
<%= will_paginate @articles %>

app/views/athletes/new.html.erb
<% provide(:title, "Add New Athlete") %>
<ol class="breadcrumb">
    <%= render_breadcrumbs :tag => :li, :separator => "" %>
  </ol>
<div class="page-header">
<h1>Create new Athlete</h1>
</div>
<%= render 'form' %>

app/views/athletes/show.html.erb
<% provide(:title, @athlete.name) %>
<ol class="breadcrumb">
    <%= render_breadcrumbs :tag => :li, :separator => "" %>
  </ol>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @athlete.name %> | Athlete Number: <%= @athlete.number %></h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-3 col-lg-3 " align="center"> <%= image_tag(@athlete.image_url, :class => "img-circle img-responsive") if @athlete.image? %> </div>

      <div class=" col-md-9 col-lg-9 "> 
        <table class="table table-user-information">
          <tbody>
            <tr>
              <td>Team :</td>
              <td><%= @athlete.team.name %></td>
            </tr>
            <tr>
              <td>Date of Birth</td>
              <td><%= @athlete.birthday.strftime('%d %B %Y') %></td>
            </tr>
         
               <tr>
                   <tr>
              <td>Gender</td>
              <td><%= @athlete.gender %></td>
            </tr>
              <tr>
              <td>Home Address</td>
              <td><%= @athlete.address %></td>
            </tr>
            <tr>
              <td>Email</td>
              <td><%= @athlete.email %></td>
            </tr>
              <td>Phone Number</td>
              <td>
              <%= @athlete.phone %>
              </td>
                 
            </tr>
           
          </tbody>
        </table>
        
        <a href="#" class="btn btn-primary">Embed</a>
      </div>
    </div>
  </div>
       <div class="panel-footer">
              <span class="pull-right">
                  <%= link_to (fa_icon "pencil"), edit_athlete_path(@athlete.id), class: "btn btn-sm btn-warning" %>
                  <%= link_to (fa_icon "trash"), athlete_path(@athlete), method: :delete, data: { confirm: "Apakah anda ingin menghapus ?" }, class: "btn btn-sm btn-danger"  %>
              </span>
          </div>
  
</div>