config/routes.rb
Rails.application.routes.draw do

  get 'teamevents/index'

  get 'embed/index'

  root 'home#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'share' => 'embed#index'
  get 'eventstanding/:event_id' => 'embed#eventstandings', as: :sharestandings
  get 'eventresults/:event_id' => 'embed#eventresults', as: :shareresults

  get 'standings/:event_id' => 'events#showstanding', as: :standing
  
  get 'set/:event_id' => 'events#setresults', as: :set
  post 'set/:event_id' => 'events#createresults'
  delete 'set/:event_id' => 'events#destroyresults'
  
  get 'ae/:event_id' => 'events#showathlete', as: :ae
  post 'ae/:event_id' => 'events#createathlete'
  delete 'ae/:event_id' => 'events#destroyathlete'
  
  get 'at/:event_id' => 'events#showteam', as: :at
  post 'at/:event_id' => 'events#createteam'
  delete 'at/:event_id' => 'events#destroyteam'

    resources :athletes
	
    resources :teams
    resources :events

end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :teamevents
	has_many :athleteevents
	has_many :athletes, through: :athleteevents
	has_many :team, through: :teamevents
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_filter :require_authorization

	add_breadcrumb "Home", :root_path
	add_breadcrumb "Events", :events_path
	
	#####
	##### view | form | show method
	#####
	
	# main index
	def index
		@events = Event.paginate(:page => params[:page], :per_page => 20).where("category = ?", "Individual")
		@events_team = Event.paginate(:page => params[:page], :per_page => 20).where("category = ?", "Team")
	end

	# create new event
	def new
		@event = Event.new
		add_breadcrumb "Add New", new_event_path
	end
	
	# edit event 
	def edit
		@event = Event.find(params[:id])
		add_breadcrumb @event.name, event_path(@event.id)
		add_breadcrumb "Edit", edit_event_path(@event.id)
	end
	
	# show result participants list
	def show
		@event = Event.find(params[:id])
		
		if @event.category == 'Individual'
			@fetchyess = Athleteevent.all.where("event_id = ? and position is not null", params[:id]).order(position: :asc)
			
			@fetchnull = Athleteevent.all.where("event_id = ? and position is null", params[:id])
			@fetch = @fetchyess+@fetchnull
			
		else
			@fetch = Teamevent.all.where("event_id = ?", params[:id]).order(position: :asc)
		end

		add_breadcrumb @event.name, event_path(@event.id)
	end
	
	# show standing participants list
	def showstanding
		@event = Event.find(params[:event_id])
		
		if @event.category == 'Individual'
			@fetch = Athleteevent.all.where("event_id = ?", params[:event_id])
			
		else
			@fetch = Teamevent.all.where("event_id = ?", params[:event_id])
		end

		add_breadcrumb @event.name, event_path(@event.id)
		add_breadcrumb "Standings", standing_path(@event.id)
	end
	
	# show athlete list for creating participants
	def showathlete

		@event = Event.find(params[:event_id])
		@athlete = Athlete.paginate(:page => params[:page], :per_page => 10)

		add_breadcrumb @event.name, event_path(@event.id)
		add_breadcrumb "Add participants", ae_path(@event.id)
	end

	# show team list for creating participants
	def showteam
		@event = Event.find(params[:event_id])
		@team = Team.paginate(:page => params[:page], :per_page => 10)

		add_breadcrumb @event.name, event_path(@event.id)
		add_breadcrumb "Add participants", at_path(@event.id)
	end
	
	# set results event
	def setresults
		@event = Event.find(params[:event_id])
		
		if @event.category == 'Individual'
			@fetch = Athleteevent.all.where("event_id = ?", params[:event_id])
			@totalfetch = @fetch.count
			@nullposition = @fetch.where.not(position: nil)
		else
			@fetch = Teamevent.all.where("event_id = ?", params[:event_id])
			@totalfetch = @fetch.count
			@nullposition = @fetch.where.not(position: nil)
		end

		add_breadcrumb @event.name, event_path(@event.id)
		add_breadcrumb "Set Results", set_path(@event.id)
	end
	
	#####
	##### create, update, destroy by post | put | delete | edit method
	#####
	
	# create new event
	def create
		@event = Event.create(event_params)
		if @event.save
	  		redirect_to events_path
	  	else
	  		render 'new'
	  	end
	end
	
	# update event
	def update
		@event = Event.find(params[:id])
		if @event.update(event_params)
	  		redirect_to @event
	  	else
	  		render 'edit'
	  	end
	end
	
	# delete event
	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		redirect_to events_path
	end
	
	# create individual event
	def createathlete
		session[:return_to] ||= request.referer
		@tran = Athleteevent.new(ae_params)
		if @tran.save
			redirect_to session.delete(:return_to)
		end
	end

	def createresults
		session[:return_to] ||= request.referer
		@id = params[:set][:id]
		@event_id = params[:event_id]
		@position = params[:set][:position]
		@category = params[:set][:category]
		if @category == "Individual"
			@tran = Athleteevent.find_by(event_id: @event_id, athlete_id: @id)
			if @tran.update_attributes(set_params)
				redirect_to session.delete(:return_to)
			else
				redirect_to set_path(@event_id)
			end
		else
			@tran = Teamevent.find_by(event_id: @event_id, team_id: @id)
			if @tran.update_attributes(set_params)
				redirect_to session.delete(:return_to)
			else
				redirect_to set_path(@event_id)
			end
		end
	end
	
	# delete individual event
	def destroyathlete
		session[:return_to] ||= request.referer
		@tran = Athleteevent.find_by(ae_params)
		@tran.destroy
		redirect_to session.delete(:return_to)
	end

	# create team event
	def createteam
		session[:return_to] ||= request.referer
		@tran = Teamevent.new(at_params)
		if @tran.save
			redirect_to session.delete(:return_to)
		end
	end
	
	# delete team event
	def destroyteam
		session[:return_to] ||= request.referer
		@tran = Teamevent.find_by(at_params)
		@tran.destroy
		redirect_to session.delete(:return_to)
	end

	def require_authorization
		redirect_to root_path unless logged_in? # or whatever you want to check
	end
	
	private
		def event_params
			params.require(:event).permit(:name, :category, :city, :venue, :province, :startdate, :finishdate, :description, :price, :image)
		end

		def ae_params
			params.require(:ae).permit(:athlete_id, :event_id)
		end

		def at_params
			params.require(:at).permit(:team_id, :event_id)
		end

		def set_params
			params.require(:set).permit(:position)
		end
		
	
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event, :html => {:class => "form-horizontal"}) do |f| %>

	<div class="form-group">
		<%= f.label :name, class: "col-sm-2 control-label" %>
		<div class="col-sm-6">
			<%= f.text_field :name, class: "form-control", placeholder: "Name" %>
		</div>
	</div>


	<div class="form-group">
		<%= f.label :description, class: "col-sm-2 control-label" %>
		<div class="col-sm-10">
			<%= f.text_area :description, class: "form-control rich", placeholder: "Event Description" %>
		</div>
	</div>
    
    <div class="form-group">
		<%= f.label :category, class: "col-sm-2 control-label" %>
		<div class="col-sm-6">
    <%= f.radio_button :category, 'Team' %> Team Event<br />			
	<%= f.radio_button :category, 'Individual' %> Individual Event
		</div>
	</div>
	
	<div class="form-group">
		<%= f.label :venue, class: "col-sm-2 control-label" %>
		<div class="col-sm-3">
			<%= f.text_field :venue, class: "form-control", placeholder: "Event Venue" %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :city, class: "col-sm-2 control-label" %>
		<div class="col-sm-3">
			<%= f.text_field :city, class: "form-control", placeholder: "City" %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :province, class: "col-sm-2 control-label" %>
		<div class="col-sm-4">
			<%= f.text_field :province, class: "form-control", placeholder: "Province" %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :price, class: "col-sm-2 control-label" %>
		<div class="col-sm-4">
			<%= f.text_field :price, class: "form-control", placeholder: "Price (HTM) - If Needed" %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :start_date, class: "col-sm-2 control-label" %>
		<div class="col-sm-4">
			<%= f.text_field :startdate, class: "form-control picker", :data => { :provide => 'datepicker' } %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :finish_date, class: "col-sm-2 control-label" %>
		<div class="col-sm-4">
			<%= f.text_field :finishdate, class: "form-control picker", :data => { :provide => 'datepicker' } %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :image, class: "col-sm-2 control-label" %>
		<div class="col-sm-5">
			<%= f.file_field :image, class: "form-control" %>
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-8">
		  <%= f.submit "Submit", class: "btn btn-default" %>
		</div>
	</div>
<% end %>

app/views/events/_menu.html.erb
<div class="pull-right"><%= link_to (fa_icon "plus-eye", text: "Show Results"), event_path(@event.id), class: active_action("show") %></div>
<div class="pull-right"><%= link_to (fa_icon "plus-eye", text: "Show Standings"), standing_path(@event.id), class: active_action("showstanding") %></div>
<div class="pull-right"><%= link_to (fa_icon "check-circle", text: "Set Event Results"), set_path(@event.id), class: active_action("setresults") %></div>
<% if @event.category == "Individual" %>
	<div class="pull-right"><%= link_to (fa_icon "plus-circle", text: "Add / Edit Participants"), ae_path(@event.id), class: active_action("showathlete") %></div>
<% else %>
	<div class="pull-right"><%= link_to (fa_icon "plus-circle", text: "Add / Edit Participants"), at_path(@event.id), class: active_action("showteam") %></div>
<% end %>

app/views/events/edit.html.erb
<% provide(:title, "Edit Event") %>
<ol class="breadcrumb">
	<%= render_breadcrumbs :tag => :li, :separator => "" %>
</ol>
<div class="page-header">
	<h1><%= @event.name %> (Edit)</h1>
</div>
<%= render 'form' %>

app/views/events/index.html.erb
<% provide(:title, "Events List") %>
<ol class="breadcrumb">
    <%= render_breadcrumbs :tag => :li, :separator => "" %>
  </ol>

<div class="pull-right"><%= link_to (fa_icon "plus-circle", text: "Add New Event"), new_event_path, class: "btn btn-sm btn-default" %></div>
<div class="page-header">
<h1>Events list</h1>
</div>
<!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#individual" aria-controls="home" role="tab" data-toggle="tab">Individual Event Tournaments</a></li>
    <li role="presentation"><a href="#team" aria-controls="profile" role="tab" data-toggle="tab">Team Event Tournaments</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="individual">
    <% if @events.present? %>
    	<% @events.each_with_index do |a, index| %>
		
		<%= link_to event_path(a.id) do %>
			<h3><%= a.name %></h3>
		<% end %>
	    <p><%= strip_tags(a.description) %></p>
	    <p>at <i class="fa fa-calendar"></i> <strong><%= a.finishdate.strftime('%d %B %Y') %></strong></p>
	<span class="pull-right">
	<%= link_to (fa_icon "plus-circle", text: "Add Participants"), ae_path(a.id), class: "btn btn-sm btn-warning" %>
		<%= link_to "Lihat", event_path(a.id), class: "btn btn-sm btn-default" %>
		<%= link_to "Edit", edit_event_path(a.id), class: "btn btn-sm btn-default" %>
		<%= link_to "Hapus", event_path(a.id), method: :delete, data: { confirm: "Apakah anda ingin menghapus Event ini?", ok: "Oke", cancel: "Batalkan" }, class: "btn btn-sm btn-danger"  %>
	</span>
	<hr>
<% end %>

<% else %>
<div class="alert alert-warning"> There are no events. <%= link_to "Create One Now.", new_event_path, class: "btn btn-sm btn-default" %> </div>
<% end %>	
<%= will_paginate @events %>
    </div>


    <div role="tabpanel" class="tab-pane" id="team">
    	
    	    <% if @events_team.present? %>
    	<% @events_team.each_with_index do |a, index| %>
		
		<%= link_to event_path(a.id) do %>
			<h3><%= a.name %></h3>
		<% end %>
	    <p><%= strip_tags(a.description) %></p>
	    <p>at <i class="fa fa-calendar"></i> <strong><%= a.finishdate.strftime('%d %B %Y') %></strong></p>
	<span class="pull-right">
		<%= link_to (fa_icon "plus-circle", text: "Add Participants"), at_path(a.id), class: "btn btn-sm btn-warning" %>
		<%= link_to "Lihat", event_path(a.id), class: "btn btn-sm btn-default" %>
		<%= link_to "Edit", edit_event_path(a.id), class: "btn btn-sm btn-default" %>
		<%= link_to "Hapus", event_path(a.id), method: :delete, data: { confirm: "Apakah anda ingin menghapus Event ini?", ok: "Oke", cancel: "Batalkan" }, class: "btn btn-sm btn-danger"  %>
	</span>
	<hr>
<% end %>

<% else %>
<div class="alert alert-warning"> There are no events. <%= link_to "Create One Now.", new_event_path, class: "btn btn-sm btn-default" %> </div>
<% end %>	
<%= will_paginate @events_team %>
    </div>
  </div>

app/views/events/new.html.erb
<% provide(:title, "Create New Event") %>
<ol class="breadcrumb">
    <%= render_breadcrumbs :tag => :li, :separator => "" %>
  </ol>
<h1>Create New Events</h1>
<%= render 'form' %>

app/views/events/setresults.html.erb
<% provide(:title, "Set Result " + @event.name) %>
<ol class="breadcrumb">
	<%= render_breadcrumbs :tag => :li, :separator => "" %>
</ol>

<div class="page-header">
	<h1>Set Result <%= @event.name %></h1>
	<%= render "menu" %>

</div>
<br>
<table class="table table-hover">
  <thead>
  <tr class="active">
  	<td colspan="5"><h4 class="text-muted text-center"><%= @event.name %> - Results</h4></td>
  </tr>
  <tr class="info">
  <th>
  		No
  	</th>
  	<th>
  		Name
  	</th>
  	<th>
  		City
  	</th>
  	<th>
  		Set Position
  	</th>
  	<th>
  		Set Point
  	</th>
  </tr>

  </thead>
  <tbody>



	<% @fetch.each_with_index do |a, index| %>
	<% if @event.category == "Individual" %>
	<tr>
	<td class="athletes no-<%= a.id %> col-md-1"><%= index + 1 %></td>
	<td class="name col-md-5"><%= a.athlete.name %></td>
	<td class="city col-md-3"><%= a.athlete.city %></td>
	<td class="edit col-md-2">
  <%= form_for set_path(a.id), :remote => false do %>
    <%= hidden_field_tag "set[id]", a.athlete.id %>
    <%= hidden_field_tag "set[category]", "Individual" %>
    <%= hidden_field_tag "set[event_id]", @event.id %>
    <%= select("set", "position", options_for_select((1..@totalfetch).map {|d| [d, d]}, selected: a.position, disabled: 7), { include_blank: true }, class: "form-control", :onchange => "this.form.submit();") %>
    <% end %></td>
	<td class="edit col-md-2">
  </td>
	</tr>
	<% else %>
	<tr>
	<td class="teams no-<%= a.id %> col-md-1"><%= index + 1 %></td>
	<td class="name col-md-5"><%= a.team.name %></td>
	<td class="city col-md-3"><%= a.team.city %></td>
	<td class="edit col-md-2">
   <%= form_for set_path(a.id), :remote => false do %>
    <%= hidden_field_tag "set[id]", a.team.id %>
    <%= hidden_field_tag "set[category]", "Team" %>
    <%= hidden_field_tag "set[event_id]", @event.id %>
    <%= select("set", "position", options_for_select((1..@totalfetch).map {|d| [d, d]}, selected: a.position), { include_blank: true }, class: "form-control", :onchange => "this.form.submit();") %>
    <% end %> 
  </td>
	<td class="edit col-md-2"><%= a.point %></td>
	</tr>
	<% end %>
	<% end %>

  </tbody>
</table>

<div class="row info">
		<div class="name col-md-12">
		<p class="text-right text-muted pull-left">ICF 2016</p>
		<p class="text-right text-muted pull-right"><i class="fa fa-calendar"></i> <strong><%= @event.startdate.strftime('%d %B %Y') %></strong> - <strong><%= @event.finishdate.strftime('%d %B %Y') %></strong></p>
		</div>
</div>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".share-modal-lg"><i class="fa fa-share-alt"></i> Embed This Results</button>

<div class="modal fade share-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">

      <input type="text" class="form-control" value="[iframe src='<%= shareresults_url(@event.id) %>' width='100%' height='800']">
      <p class="text-muted text-center">Copy this code into site post</p>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<% provide(:title, @event.name) %>
<ol class="breadcrumb">
	<%= render_breadcrumbs :tag => :li, :separator => "" %>
</ol>

<div class="page-header">
	<h1><%= @event.name %></h1>
	<%= render "menu" %>

</div>
<br>
<table class="table table-hover">
  <thead>
  <tr class="active">
  	<td colspan="5"><h4 class="text-muted text-center"><%= @event.name %> - Results</h4></td>
  </tr>
  <tr class="info">
  <th>
  		Position
  	</th>
  	<th>
  		<%= (@event.category == "Individual") ? "Athlete Name" : "Team Name" %>
  	</th>
  	<th>
  		City
  	</th>
  	<th>
  		Point
  	</th>
  </tr>

  </thead>
  <tbody>



	<% @fetch.each_with_index do |a, index| %>
	<% if @event.category == "Individual" %>
	<tr>
	<td class="athletes no-<%= a.id %> col-md-1"><%= a.position %></td>
	<td class="name col-md-5"><%= a.athlete.name %></td>
	<td class="city col-md-3"><%= a.athlete.city %></td>
	<td class="edit col-md-2"><%= a.point %></td>
	</tr>
	<% else %>
	<tr>
	<td class="teams no-<%= a.id %> col-md-1"><%= a.position %></td>
	<td class="name col-md-5"><%= a.team.name %></td>
	<td class="city col-md-3"><%= a.team.city %></td>
	<td class="edit col-md-2"><%= a.point %></td>
	</tr>
	<% end %>
	<% end %>

  </tbody>
</table>

<div class="row info">
		<div class="name col-md-12">
		<p class="text-right text-muted pull-left">ICF 2016</p>
		<p class="text-right text-muted pull-right"><i class="fa fa-calendar"></i> <strong><%= @event.startdate.strftime('%d %B %Y') %></strong> - <strong><%= @event.finishdate.strftime('%d %B %Y') %></strong></p>
		</div>
</div>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".share-modal-lg"><i class="fa fa-share-alt"></i> Embed This Results</button>

<div class="modal fade share-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">

      <input type="text" class="form-control" value="[iframe src='<%= shareresults_url(@event.id) %>' width='100%' height='800']">
      <p class="text-muted text-center">Copy this code into site post</p>
    </div>
  </div>
</div>

app/views/events/showathlete.html.erb
<% provide(:title, @event.name) %>
<ol class="breadcrumb">
	<%= render_breadcrumbs :tag => :li, :separator => "" %>
</ol>
<div class="page-header">
	<h2>Add Athletes for <%= @event.name %></h2>
	<%= render "menu" %>
</div>
<br>
<ul class="list-group">
<% @athlete.each_with_index do |a, index| %>
  <li class="list-group-item">
	<div class="row">
		<div class="athletes no-<%= a.id %> col-md-2"><%= @athlete.offset + index + 1 %></div>
		<div class="name col-md-4"><%= a.name %></div>
		<div class="city col-md-3"><%= a.city %></div>
		<div class="edit col-md-3">

			<%= button_to ae_path(params[:event_id]), :method => :post, params: {:"ae[athlete_id]" => a.id, :"ae[event_id]" => params[:event_id]}, class: "btn btn-danger", :disabled => a.athleteevents.where(:athlete_id => a.id, :event_id => params[:event_id]).present?, form_class: "button-thing button-ajax-form", :data => { :id => a.id } do %>
			<%= ("<i class='fa fa-plus-square-o'></i> Add").html_safe %>
			<% end %>

			<%= button_to ae_path(params[:event_id]), :method => :delete, params: {:"ae[athlete_id]" => a.id, :"ae[event_id]" => params[:event_id]}, class: "btn btn-default", :disabled => !a.athleteevents.where(:athlete_id => a.id, :event_id => params[:event_id]).present?, form_class: "button-thing button-ajax-form", :data => { :id => a.id } do %>
			<%= ("<i class='fa fa-close'></i>").html_safe %>
			<% end %>


		</div>
	</div>
</li>
<% end %>
</ul>
	
<%= will_paginate @athlete %>

app/views/events/showstanding.html.erb
<% provide(:title, @event.name) %>
<ol class="breadcrumb">
	<%= render_breadcrumbs :tag => :li, :separator => "" %>
</ol>

<div class="page-header">
	<h1><%= @event.name %></h1>
	<%= render "menu" %>

</div>
<br>
	<table class="table table-hover">
  <thead>
  <tr class="active">
  	<td colspan="5"><h4 class="text-muted text-center"><%= @event.name %> - Standings</h4></td>
  </tr>
  <tr class="info">
  <th>
  		No
  	</th>
  	<th>
  		Name
  	</th>
  	<th>
  		City
  	</th>
  	<th>
  		Position
  	</th>
  	<th>
  		Point
  	</th>
  </tr>

  </thead>
  <tbody>

	<% @fetch.each_with_index do |a, index| %>
	<% if @event.category == "Individual" %>
	<tr>
	<td class="athletes no-<%= a.id %> col-md-1"><%= index + 1 %></td>
	<td class="name col-md-5"><%= a.athlete.name %></td>
	<td class="city col-md-3"><%= a.athlete.city %></td>
	<td class="edit col-md-2"><%= a.position %></td>
	<td class="edit col-md-2"><%= a.point %></td>
	</tr>
	<% else %>
	<tr>
	<td class="teams no-<%= a.id %> col-md-1"><%= index %></td>
	<td class="name col-md-5"><%= a.team.name %></td>
	<td class="city col-md-3"><%= a.team.city %></td>
	<td class="edit col-md-2"><%= a.position %></td>
	<td class="edit col-md-2"><%= a.point %></td>
	</tr>
	<% end %>
	<% end %>

  </tbody>
</table>

<div class="row info">
		<div class="name col-md-12">
		<p class="text-right text-muted pull-left">ICF 2016</p>
		<p class="text-right text-muted pull-right"><i class="fa fa-calendar"></i> <strong><%= @event.startdate.strftime('%d %B %Y') %></strong> - <strong><%= @event.finishdate.strftime('%d %B %Y') %></strong></p>
		</div>
</div>


<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".share-modal-lg"><i class="fa fa-share-alt"></i> Embed This Standings</button>

<div class="modal fade share-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">

      <input type="text" class="form-control" value="[iframe src='<%= sharestandings_url(@event.id) %>' width='100%' height='800']">
      <p class="text-muted text-center">Copy this code into site post</p>
    </div>
  </div>
</div>

app/views/events/showteam.html.erb
<% provide(:title, @event.name) %>
<ol class="breadcrumb">
	<%= render_breadcrumbs :tag => :li, :separator => "" %>
</ol>
<div class="page-header">
	<h2>Add Teams for <%= @event.name %></h2>
	<%= render "menu" %>
</div>
<br>
<ul class="list-group">
<% @team.each_with_index do |a, index| %>
  <li class="list-group-item">
	<div class="row">
		<div class="teams no-<%= a.id %> col-md-2"><%= @team.offset + index + 1 %></div>
		<div class="name col-md-4"><%= a.name %></div>
		<div class="city col-md-3"><%= a.city %></div>
		<div class="edit col-md-3">

			<%= button_to at_path(params[:event_id]), :method => :post, params: {:"at[team_id]" => a.id, :"at[event_id]" => params[:event_id]}, class: "btn btn-danger", :disabled => a.teamevents.where(:team_id => a.id, :event_id => params[:event_id]).present?, form_class: "button-thing button-ajax-form" do %>
			<%= ("<i class='fa fa-plus-square-o'></i> Add").html_safe %>
			<% end %>

			<%= button_to at_path(params[:event_id]), :method => :delete, params: {:"at[team_id]" => a.id, :"at[event_id]" => params[:event_id]}, class: "btn btn-default", :disabled => !a.teamevents.where(:team_id => a.id, :event_id => params[:event_id]).present?, form_class: "button-thing button-ajax-form" do %>
			<%= ("<i class='fa fa-close'></i>").html_safe %>
			<% end %>


		</div>
	</div>
</li>
<% end %>
</ul>
	
<%= will_paginate @team %>