config/routes.rb
Rails.application.routes.draw do

  get 'teamevents/index'

  get 'embed/index'

  root 'home#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'share' => 'embed#index'
  get 'eventstanding/:event_id' => 'embed#eventstandings', as: :sharestandings
  get 'eventresults/:event_id' => 'embed#eventresults', as: :shareresults

  get 'standings/:event_id' => 'events#showstanding', as: :standing
  
  get 'set/:event_id' => 'events#setresults', as: :set
  post 'set/:event_id' => 'events#createresults'
  delete 'set/:event_id' => 'events#destroyresults'
  
  get 'ae/:event_id' => 'events#showathlete', as: :ae
  post 'ae/:event_id' => 'events#createathlete'
  delete 'ae/:event_id' => 'events#destroyathlete'
  
  get 'at/:event_id' => 'events#showteam', as: :at
  post 'at/:event_id' => 'events#createteam'
  delete 'at/:event_id' => 'events#destroyteam'

    resources :athletes
	
    resources :teams
    resources :events

end

app/views/layouts/_left.html.erb
<div class="panel panel-default">
  <div class="panel-body">
	<ul class="nav nav-pills nav-stacked">
	<li role="presentation"><%= link_to "Home", root_path, class: active_controller("home")[0] %></li>
	<li role="presentation"><%= link_to "Athletes", athletes_path, class: active_controller("athletes")[0] %></li>
	<li role="presentation"><%= link_to "Teams", teams_path, class: active_controller("teams")[0] %></li>
	<li role="presentation"><%= link_to "Events", events_path, class: active_controller("events")[0] %>
		<!-- <div style="padding-left:3px;">
      <ul id="drilldown-event" class="nav nav-pills nav-stacked <%= active_controller('events')[1] %>">
        <li><a href="#">Road</a></li>
        <li><a href="#">Track</a></li>
        <li><a href="#">Cross Country</a></li>
        <li><a href="#">Downhill</a></li>
        <li><a href="#">BMX</a></li>
      </ul>
    </div> -->
	</li>
	</ul>
</div>
</div>

app/views/layouts/_top.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">ICF Dashboard</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Account Settings</a></li>
        <li><%= link_to "Log out", logout_path, method: :delete %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | ICF Dashboard</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if logged_in? && (check_embed? == false) %>
	<div class="container">
	<%= render 'layouts/top' %>
	<div class="row">
		<div class="col-md-2">
			<%= render 'layouts/left' %>
		</div>
		<div class="col-md-10">
			<%= yield %>
		</div>
	</div>
	
	</div>
	
	<% else %>
		<%= yield %>
	<% end %>	

<footer class="footer">
  <div class="container">
    <p class="text-muted text-center">PB ISSI | ICF - 2016</p>
  </div>
</footer>
</body>
</html>